/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.NhanVienDAO;
import entity.NhanVien;
import utils.Auth;
import utils.MsgBox;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Ly Tinh Nhiem
 */
public class DangNhapJDiaLog extends javax.swing.JDialog {

    NhanVienDAO dao = new NhanVienDAO();
    boolean showPass = false;

    /**
     * Creates new form loginJDialog
     *
     * @param parent
     * @param modal
     */
    public DangNhapJDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Login");
        setLocationRelativeTo(parent);
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn chắc muốn thoát chứ?")) {
            System.exit(0);
        }
    }

    void dangNhap() {
        String username = txtTenDangNhap.getText();
        String password = new String(txtMatKhau.getPassword());
        NhanVien nhanVien = dao.selectById(username);
        if (nhanVien == null) {
            MsgBox.alert(this, "Sai username!");
        } else if (!password.equals(nhanVien.getMatKhau())) {
            MsgBox.alert(this, "Sai password!");
        } else {
            Auth.user = nhanVien;
            this.dispose();
            new ChaoDialog(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRight = new javax.swing.JPanel();
        txtTenDangNhap = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblEye = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPwdIcon = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnKetThuc = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenDangNhap.setToolTipText("");
        txtTenDangNhap.setBorder(null);
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });
        pnlRight.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 200, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 255, 0));
        pnlRight.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 200, 10));

        lblEye.setForeground(new java.awt.Color(255, 255, 255));
        lblEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        lblEye.setText(" ");
        lblEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEyeMouseClicked(evt);
            }
        });
        pnlRight.add(lblEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 50, 30));

        txtMatKhau.setBorder(null);
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        pnlRight.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 255, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 255, 0));
        pnlRight.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 200, 10));

        lblPwdIcon.setBackground(new java.awt.Color(255, 255, 0));
        lblPwdIcon.setForeground(new java.awt.Color(255, 102, 0));
        lblPwdIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPwdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_password_20px.png"))); // NOI18N
        pnlRight.add(lblPwdIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        lblUserIcon.setBackground(new java.awt.Color(255, 255, 0));
        lblUserIcon.setForeground(new java.awt.Color(255, 102, 0));
        lblUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_user_20px.png"))); // NOI18N
        pnlRight.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 30, 30));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 204, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ĐĂNG NHẬP");
        pnlRight.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 220, 40));

        btnKetThuc.setBackground(new java.awt.Color(153, 255, 204));
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        btnKetThuc.setContentAreaFilled(false);
        btnKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKetThuc.setFocusPainted(false);
        btnKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKetThucMousePressed(evt);
            }
        });
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        pnlRight.add(btnKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 100, 30));

        btnDangNhap.setBackground(new java.awt.Color(153, 255, 204));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setFocusPainted(false);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDangNhapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseReleased(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnlRight.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login100x100.png"))); // NOI18N
        pnlRight.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangNhapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseReleased
        btnDangNhap.setOpaque(false);
    }//GEN-LAST:event_btnDangNhapMouseReleased

    private void btnDangNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMousePressed
        btnDangNhap.setOpaque(true);
        btnDangNhap.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnDangNhapMousePressed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnKetThucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKetThucMousePressed

    }//GEN-LAST:event_btnKetThucMousePressed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void lblEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeMouseClicked
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/icons/eye.png"));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/icons/hide.png"));
        if (showPass == false) {
            txtMatKhau.setEchoChar((char) 0);
            showPass = true;
            lblEye.setIcon(icon2);
        } else {
            txtMatKhau.setEchoChar('*');
            showPass = false;
            lblEye.setIcon(icon1);
        }
    }//GEN-LAST:event_lblEyeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
 /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDiaLog dialog = new DangNhapJDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEye;
    private javax.swing.JLabel lblPwdIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
